id: eba13d44f00048afa24791a7fb8e1727
initial_creation_type: ocr
source_metadata:
  volumes:
    34e8c5cd89fd414c8c3ca86458205570:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: དཀོན་མཆོག་གསུམ་གྱི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
